[tool.poetry]
name = "c4a0"
version = "0.1.0"
description = ""
authors = ["Advait Shinde <advait.shinde@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytorch = "^1.0.2"
pytorch-lightning = "^2.1.3"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
