[tool.poetry]
name = "c4a0"
version = "0.1.0"
description = ""
authors = ["Advait Shinde <advait.shinde@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytorch-lightning = "^2.1.3"
numpy = "^1.26.2"
einops = "^0.7.0"
torchmetrics = "^1.2.1"
tensorboardx = "^2.6.2.2"
tensorboard = "^2.15.1"
pytest-asyncio = "^0.23.3"
tqdm = "^4.66.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.9"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
