[project]
name = "c4a0"
version = "0.1.0"
description = ""
authors = [{ name = "Advait Shinde", email = "advait.shinde@gmail.com" }]
dependencies = [
  "pytorch-lightning>=2.1.3",
  "numpy>=1.26.2",
  "einops>=0.8.0",
  "torchmetrics>=1.2.1",
  "tensorboardx>=2.6.2.2",
  "tensorboard>=2.15.1",
  "tqdm>=4.66.1",
  "jupyterlab>=4.0.10",
  "pydantic>=2.5.3",
  "clipstick>=0.5.1",
  "tabulate>=0.9.0",
  "matplotlib>=3.8.2",
  "maturin>=1.6.0",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[tool.rye]
managed = true
dev-dependencies = [
  "pytest>=7.4.3",
  "pytest-asyncio>=0.23.3",
  "pyright>=1.1.345",
  "jupyterlab>=4.0.10",
  "pandas>=2.1.4",
  "rankit>=0.3.3",
]

[tool.pyright]
typeCheckingMode = "basic"
extraPaths = ["src", "tests"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
filterwarnings = [
  # Disable warnings we get form pytorch lightning that clutter pytest output
  "ignore:pkg_resources is deprecated.*:DeprecationWarning",
  "ignore:Deprecated call to `pkg_resources.declare_namespace`.*:DeprecationWarning",
  "ignore:Deprecated call to `pkg_resources.declare_namespace.*:DeprecationWarning",
  "ignore:You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet.*",
]
