[tool.poetry]
name = "c4a0"
version = "0.1.0"
description = ""
authors = ["Advait Shinde <advait.shinde@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytorch-lightning = "^2.1.3"
numpy = "^1.26.2"
einops = "^0.7.0"
torchmetrics = "^1.2.1"
tensorboardx = "^2.6.2.2"
tensorboard = "^2.15.1"
tqdm = "^4.66.1"
jupyterlab = "^4.0.10"
pydantic = "^2.5.3"
clipstick = "^0.5.1"
tabulate = "^0.9.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.9"
pytest = "^7.4.3"
pytest-asyncio = "^0.23.3"
pyright = "^1.1.345"
jupyterlab = "^4.0.10"
pandas = "^2.1.4"
rankit = "^0.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "basic"
extraPaths = ["src"]

[tool.pytest.ini_options]
filterwarnings = [
  # Disable warnings we get form pytorch lightning that clutter pytest output
  "ignore:pkg_resources is deprecated.*:DeprecationWarning",
  "ignore:Deprecated call to `pkg_resources.declare_namespace`.*:DeprecationWarning",
  "ignore:Deprecated call to `pkg_resources.declare_namespace.*:DeprecationWarning",
  "ignore:You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet.*",
]
