[package]
name = "c4a0_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# pyo3 = { version = "0.21.2", features = ["extension-module"] }
approx = "0.5.1"
more-asserts = "0.3.1"
crossbeam = "0.8.4"
num_cpus = "1.16.0"
rand = "0.8.5"
crossbeam-channel = "0.5.13"
burn = { version = "0.13.2", features = ["candle", "wgpu", "train", "ndarray"] }
tui = "0.19.0"
metrics = "0.23.0"
wgpu = "0.20.1"
ndarray = "0.15.6"
num-traits = "0.2.19"
