name: c4a0 CI

on:
  # Triggers the workflow on push events for all branches
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Rust actions
      - name: install rust
        run: rustup update stable && rustup default stable
      - name: cargo test
        working-directory: rust
        run: cargo test

      # Python actions
      - uses: actions/setup-python@v4
      - uses: yezz123/setup-uv@v4
      - run: uv sync
      - run: uv run ruff check
      - run: uv run maturin build --release
