name: c4a0 CI

on:
  # Triggers the workflow on push or pull request events for all branches
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python from .python-version
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --with=dev

      - name: ruff check (lint)
        run: |
          poetry run ruff check

      - name: ruff format
        run: |
          poetry run ruff format --check

      - name: pyright (typechecking)
        run: |
          poetry run pyright

      - name: pytest
        run: |
          poetry run pytest
