name: c4a0 CI

on:
  # Triggers the workflow on push or pull request events for all branches
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Rust actions
      - name: install rust
        run: rustup update stable && rustup default stable
      - name: cargo test
        working-directory: rust
        run: cargo test

      # Python actions
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
      - run: rye sync
      - run: rye lint
      - run: rye run pyright
      - run: rye run pytest
      - run: rye run maturin build --release
